const styles = {
  Container: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: "1.5rem",
    padding: "2rem",
  },
  style: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "1.5rem",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#28a745",
    textAlign: "center",
    cursor: "pointer",
    transition: "transform 0.2s",
    minWidth: "300px",
    maxWidth: "calc(25% - 1.5rem)",
    flex: "1 1 calc(25% - 1.5rem)",
  },
  style2: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "1.5rem",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#dc3545",
    textAlign: "center",
    transition: "transform 0.2s",
    minWidth: "300px",
    maxWidth: "calc(25% - 1.5rem)",
    flex: "1 1 calc(25% - 1.5rem)",
  },
  clinic: {
    border: "1px solid #ddd",
    borderRadius: "8px",
    padding: "1.5rem",
    boxShadow: "0 4px 8px rgba(0, 0, 0, 0.1)",
    backgroundColor: "#5bc0de",
    textAlign: "center",
    transition: "transform 0.2s",
    minWidth: "300px",
    maxWidth: "calc(25% - 1.5rem)",
    flex: "1 1 calc(25% - 1.5rem)",
  },
  doctor: {
    backgroundColor: "#f9f9f9",
    padding: "1rem",
    borderRadius: "8px",
    marginBottom: "1rem",
  },
  centerBig: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: "2rem",
  },
  inputNote: {
    width: "100%",
    minHeight: "100px",
    padding: "10px",
    fontSize: "16px",
    lineHeight: "1.5",
    boxSizing: "border-box",
    resize: "none",
  },
};

export default styles;
